6 core security und authentification einbinden
jstHH/Camping-App pull request #22
Opened 2022-05-20 14:17 UTC by jstHH

Security und Login im Backend und Frontend hinzugefügt.

2022-05-21 06:27 UTC, danielschwarz-neuefische requested changes
Super gemacht, Authentifizierung habe ich ausprobiert und scheint gut zu funktionieren!

Ausrüstung hinzufügen, etc. klappt noch nicht - aber soweit ich das gesehen habe ist es einfach noch nicht implementiert.

Bitte vor dem mergen noch das Secret (wie von Marlin angemerkt) auslagern.

2022-05-21 06:27 UTC, danielschwarz-neuefische commented on backend/src/main/java/com/example/backend/security/controller/AppUserAuthController.java
> +import com.example.backend.security.model.AppUser;
🐜 unused import

2022-05-21 06:27 UTC, danielschwarz-neuefische commented on backend/src/main/java/com/example/backend/security/service/JWTUtilService.java
> +    private String JWT_SECRET;
🐜 Kleinigkeit: SonarLint zeigt an, dass der Variablenname nicht der Konvention entspricht. Da es nicht `final static` ist, wäre hier `jwtSecret` oder dergleichen üblich.

2022-05-22 16:42 UTC, jstHH commented on frontend/src/context/AuthProvider.tsx
> +            .catch(() => toast.error("Login failed. Credentials invalid?"))
Der Toast ist ein Überbleibsel, die Toasts werden durch Alert und/oder Bootstrap Toasts ersetzt. Ticket ist erstellt

2022-05-22 16:46 UTC, merged